services:
  rabbitmq:
    image: rabbitmq:4-management
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    ports:
      - 5672:5672
      - 15672:15672
  
  user_database: 
    image: postgres:18
    env_file:
      - ./apps/users/.env
    ports:
      - 5432:5432